### ISSUE TITLE
Installing the project with Python 3.9.5 fails

### ISSUE THREAD

**Issue by moracabanas** [bes-dev/random_face#3]
It seems `openvino` isn't supporting python 3.8+ yet

```
RuntimeError

  Unable to find installation candidates for openvino (2021.3.0)
```

**Comment by bes-dev** [comment]
@moracabanas hey, which OS do you use? It works well for me with MacOS 11.2 (Python 3.8.6) and Ubuntu 20.04 (Python 3.8.6)

**Comment by moracabanas** [comment]
Thanks for your fast reply.  I'm on windows 10 python 3.9.5 with Poetry 

Checking on Openvino last release is not updated to be 3.9 compatoble yet 

![image](https://user-images.githubusercontent.com/4382333/120922760-3bde0980-c6cb-11eb-9223-2052bbc56c72.png)

**Comment by bes-dev** [comment]
@moracabanas as you can find in [Requirements](https://github.com/bes-dev/random_face#requirements), our library doesn't support python 3.9+ too. But you can try to build openvino and our library manually, I think that OpenVINO should be workable with python 3.9 but there isn't official support because it didn't tested yet.

**Comment by moracabanas** [comment]
Sorry about that I misunderstood 3.8+. I thought 3.8+ means that you can use any >3.8 python version.

Thanks you for taking your time to provide a solution. For the moment I will try to use `pyenv` to manage python system version so Poetry initializes the project with the correct version for developement. Then I use a docker container with the target Python version.
I was looking for a solution because I have a background process holding python 3.9.5 for the next 5h 😂 so I am stuck. 
No hurries and thanks you so much!

**Comment by bes-dev** [comment]
@moracabanas thanks for your feedback, I fixed readme to clear up the confusion

**Comment by moracabanas** [comment]
New feedback 
I am trying to run the demo on python 3.8 (windows 10) following the next steps:

```python 
python -m random_face.demo
```
And the last traceback i get is
```error
File "......3.8.0\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

Looking for this error I found a stackoverflow [discussion ](https://stackoverflow.com/a/47476794) and there seems to be an [open issue](https://github.com/erikrose/blessings/issues/21) reffered to _curses_ python library on windows since 2012 

The last comment refers to using [blessed library](https://blessed.readthedocs.io/en/latest/intro.html#requirements) which is windows compatible 

I tried to testing on my linux container but it won't work as there is no X server attached:

```error
Processing time: 0.30084681510925293 s.


Press 'q' for quitqt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.

This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

             Aborted
```

**Comment by bes-dev** [comment]
@moracabanas thanks for feedback. We migrated to 'blessed' library. Please try to use new version of our library.

**Comment by moracabanas** [comment]
That was fast! 
Working as expected! 
Thanks you so much!
